services:
  database:
    image: "postgres:latest"
    container_name: clean_postgres_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-postgres-clean:/var/lib/postgresql/data

  clean-app:
    image: diegoneves/clean-architecture:latest
    container_name: clean_architecture_demo
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DB_HOST=clean_postgres_db
      - DB_PORT=5432
    entrypoint: sh -c "dockerize -wait tcp://clean_postgres_db:5432 -timeout 60s && java -jar target/clean-architecture.jar"

volumes:
  db-postgres-clean: