services:
  database-dev:
    image: "mysql:latest"
    container_name: clean_mysql_db_dev
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-mysql-clean-dev:/var/lib/mysql

volumes:
  db-mysql-clean-dev:
