services:
  database:
    image: "mysql:latest"
    container_name: clean_mysql_db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-mysql-clean:/var/lib/postgresql/data

  clean-app:
    image: diegoneves/clean-architecture:0.1.0
    container_name: clean_architecture_demo
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DB_HOST=clean_mysql_db
      - DB_PORT=3306
    entrypoint: sh -c "dockerize -wait tcp://clean_mysql_db:3306 -timeout 60s && java -jar target/clean-architecture.jar"

volumes:
  db-mysql-clean: