services:
  database:
    image: "postgres:latest"
    container_name: clean_postgres_db_dev
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-postgres-clean-dev:/var/lib/postgresql/data

volumes:
  db-postgres-clean-dev: