name: CI Develop

on:
  pull_request: # Essas linhas indica que toda pull_request apontada para a branch develop sera executado a CI
    branches:
      - develop
jobs:
  check-application:
    strategy:
      matrix:
        ubuntu: ['ubuntu-latest']
        java: ['17']
    runs-on: ${{ matrix.ubuntu }}
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}

      - name: Setup Maven
        run: |
            sudo apt-get install -y maven

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test
